//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistantDetail
    {
        public int AssitantDetailId { get; set; }
        public int DepartmentId { get; set; }
        public int AssistantId { get; set; }
    
        public virtual Assistant Assistant { get; set; }
        public virtual Department Department { get; set; }
    }
}
